---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hot
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cold
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "clickhouse.fullname" . }}
data:
  config.xml: |
    <?xml version="1.0"?>
    <yandex>
      <storage_configuration>
        <disks>
          <hot>
            <type>local</type>
            <path>/var/lib/clickhouse/data/hot/</path>
          </hot>
          <cold>
            <type>local</type>
            <path>/var/lib/clickhouse/data/cold/</path>
          </cold>
        </disks>
        <policies>
          <hot>
            <volumes>
              <single_volume>
                <disk>hot</disk>
              </single_volume>
            </volumes>
            <move_factor>{{ .Values.configMap.moveFactor }}</move_factor>
            <max_data_part_size_bytes>{{ .Values.storage.hot.size }}</max_data_part_size_bytes>
          </hot>
          <cold>
            <volumes>
              <single_volume>
                <disk>cold</disk>
              </single_volume>
            </volumes>
            <move_factor>{{ .Values.configMap.moveFactor }}</move_factor>
            <max_data_part_size_bytes>{{ .Values.storage.cold.size }}</max_data_part_size_bytes>
          </cold>
        </policies>
      </storage_configuration>
    </yandex>
