apiVersion: v1
kind: Service
metadata:
  name: {{ template "clickhouse.fullname" . }}
spec:
  selector:
    app: {{ template "clickhouse.name" . }}
  ports:
    - port: 8123
      targetPort: http
      protocol: TCP
      name: http
